language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libtidy-0.99-0
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
