name: changelog

on:
  pull_request:
    branches:
    - '**'
    path:
    # Only run if changes were made in markdown/
    - 'markdown/**'

# permissions:
#   pull-requests: write

jobs:
  validate:

    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    - uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: 'docs/changelog.md'
        missingUpdateErrorMessage: |
          @${{ github.actor }}, thank you for your contribution. It appears that you have not added a comment to the
          changelog describing the changes you have made. Doing so will help to ensure your contribution is accepted.

          Please see the [Contributing Guide](https://python-markdown.github.io/contributing/#changelog) for details.
