name: changelog

on:
  pull_request:
    branches:
    - '**'
    path:
    # Only run if changes were made in markdown/ or the changelog
    - 'markdown/**'
    - 'docs/changelog.md'

# permissions:
#   pull-requests: write

jobs:
  validate:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ensure Changelog Entry Made
      uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: 'docs/changelog.md'
        missingUpdateErrorMessage: |
          @${{ github.actor }}, thank you for your contribution. It appears that you have not added a comment to the
          changelog describing the changes you have made. Doing so will help to ensure your contribution is accepted.

          Please see the [Contributing Guide](https://python-markdown.github.io/contributing/#changelog) for details.
    - name: Validate Changelog
      if: success()
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: error
        path: docs/changelog.md
