name: bot

on:
  pull_request:
    branches:
    - '**'

jobs:
  require_changelog:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mskelton/changelog-reminder-action@v1
      with:
        # Match any file in the docs/change_log/ dir.
        changelogRegex: "docs/change_log/.*"
        # Only require changelog update if changes were made in markdown/
        include: "markdown/.*"
        message: ""
