# This workflow will install Python dependencies and run tox tests with a matrix of Python versions.
# Uses https://github.com/ymyzk/tox-gh-actions to define build matrix in the tox.ini file.

name: tox tests

on: [pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Install dependencies
      run: |
        sudo apt-get install libtidy-dev
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        npm install -g markdown-link-check
        sudo apt-get install aspell aspell-en
    - name: Test with tox
      run: tox
